apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service-dev
  namespace: dev
  labels:
    app: cast-service
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
      environment: dev
  template:
    metadata:
      labels:
        app: cast-service
        environment: dev
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: cast-service
        image: nguetsop/jenskin-cicd-projekt:cast-service-latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: "postgresql://cast_db_username:cast_db_password@cast-db:5432/cast_db_dev"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
