apiVersion: v1
kind: Service
metadata:
  name: cast-db
  namespace: dev
  labels:
    app: cast-db
    environment: dev
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: cast-db
    environment: dev
