apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db-dev
  namespace: dev
  labels:
    app: cast-db
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
      environment: dev
  template:
    metadata:
      labels:
        app: cast-db
        environment: dev
    spec:
      containers:
      - name: postgres
        image: postgres:12.1-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "cast_db_username"
        - name: POSTGRES_PASSWORD
          value: "cast_db_password"
        - name: POSTGRES_DB
          value: "cast_db_dev"
        volumeMounts:
        - name: postgres-data-cast
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: postgres-data-cast
        persistentVolumeClaim:
          claimName: postgres-data-cast-dev
