apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service-dev
  namespace: dev
  labels:
    app: movie-service
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
      environment: dev
  template:
    metadata:
      labels:
        app: movie-service
        environment: dev
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: movie-service
        image: nguetsop/jenskin-cicd-projekt:movie-service-latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: "postgresql://movie_db_username:movie_db_password@movie-db:5432/movie_db_dev"
        - name: CAST_SERVICE_HOST_URL
          value: "http://cast-service:8000/api/v1/casts/"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
