apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: dev
  labels:
    app: nginx
    environment: dev
spec:
  selector:
    app: nginx          
    environment: dev    
  ports:
  - protocol: TCP
    port: 80          
    targetPort: 8080   
  type: LoadBalancer