# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-data-cast-dev
#   namespace: dev
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-data-movie-dev
#   namespace: dev
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-cast-dev
  namespace: dev
  labels:
    app: cast-db
    environment: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-movie-dev
  namespace: dev
  labels:
    app: movie-db
    environment: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path