apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: staging
  labels:
    app: cast-service
    environment: staging
    component: api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: cast-service
    environment: staging