apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service-staging
  namespace: staging
  labels:
    app: cast-service
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cast-service
      environment: staging
  template:
    metadata:
      labels:
        app: cast-service
        environment: staging
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: cast-service
        image: nguetsop/jenskin-cicd-projekt:cast-service-latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: "postgresql://cast_db_username:cast_db_password@cast-db:5432/cast_db_dev"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "400m"
