apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db-staging
  namespace: staging
  labels:
    app: movie-db
    environment: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie-db
      environment: staging
  template:
    metadata:
      labels:
        app: movie-db
        environment: staging
    spec:
      containers:
      - name: postgres
        image: postgres:12.1-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: movie-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: movie-db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: movie-db-secret
              key: POSTGRES_DB
        volumeMounts:
        - name: postgres-data-movie
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: postgres-data-movie
        persistentVolumeClaim:
          claimName: postgres-data-movie-staging