apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service-staging
  namespace: staging
  labels:
    app: movie-service
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-service
      environment: staging
  template:
    metadata:
      labels:
        app: movie-service
        environment: staging
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: movie-service
        image: nguetsop/movie-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: "postgresql://movie_db_username:movie_db_password@movie-db:5432/movie_db_dev"
        - name: CAST_SERVICE_HOST_URL
          value: "http://cast-service:8000/api/v1/casts/"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "400m"
