apiVersion: v1
kind: Service
metadata:
  name: movie-db
  namespace: staging
  labels:
    app: movie-db
    environment: staging
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: movie-db
    environment: staging
