apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-staging
  namespace: staging
  labels:
    app: nginx
    environment: staging
    tier: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
      environment: staging
  template:
    metadata:
      labels:
        app: nginx
        environment: staging
        tier: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
     
      containers:
      - name: nginx
        image: nginx:1.21-alpine
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
       
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
       
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "100m"
     
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config