apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service-qa
  namespace: qa
  labels:
    app: cast-service
    environment: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cast-service
      environment: qa
  template:
    metadata:
      labels:
        app: cast-service
        environment: qa
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: cast-service
        image: nguetsop/jenskin-cicd-projekt:cast-service-latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: "postgresql://cast_db_username:cast_db_password@cast-db:5432/cast_db_dev"
        resources:
          requests:
            memory: "96Mi"
            cpu: "75m"
          limits:
            memory: "384Mi"
            cpu: "300m"
