# apiVersion: v1
# kind: Service
# metadata:
#   name: cast-service
#   namespace: qa
#   labels:
#     app: cast-service
#     environment: qa
# spec:
#   type: ClusterIP
#   ports:
#   - port: 8000
#     targetPort: 8000
#     protocol: TCP
#   selector:
#     app: cast-service
#     environment: qa


apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: qa
  labels:
    app: cast-service
    environment: qa
    component: api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: cast-service
    environment: qa