apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  namespace: qa
  labels:
    app: cast-service
    environment: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: votre-username/cast-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres:5432/casts_qa"
        - name: ENVIRONMENT
          value: "qa"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"