apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: qa
  labels:
    app: cast-service
spec:
  selector:
    app: cast-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP