# apiVersion: v1
# kind: Service
# metadata:
#   name: movie-db
#   namespace: qa
#   labels:
#     app: movie-db
#     environment: qa
# spec:
#   type: ClusterIP
#   ports:
#   - port: 5432
#     targetPort: 5432
#     protocol: TCP
#   selector:
#     app: movie-db
#     environment: qa


apiVersion: v1
kind: Service
metadata:
  name: movie-db
  namespace: qa
  labels:
    app: movie-db
    environment: qa
    component: database
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: movie-db
    environment: qa