apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db-qa
  namespace: qa
  labels:
    app: movie-db
    environment: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
      environment: qa
  template:
    metadata:
      labels:
        app: movie-db
        environment: qa
    spec:
      containers:
      - name: postgres
        image: postgres:12.1-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "movie_db_username"
        - name: POSTGRES_PASSWORD
          value: "movie_db_password"
        - name: POSTGRES_DB
          value: "movie_db_dev"
        volumeMounts:
        - name: postgres-data-movie
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "96Mi"
            cpu: "75m"
          limits:
            memory: "384Mi"
            cpu: "300m"
      volumes:
      - name: postgres-data-movie
        persistentVolumeClaim:
          claimName: postgres-data-movie-qa
