apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service-qa
  namespace: qa
  labels:
    app: movie-service
    environment: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-service
      environment: qa
  template:
    metadata:
      labels:
        app: movie-service
        environment: qa
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: movie-service
        image: nguetsop/movie-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: "postgresql://movie_db_username:movie_db_password@movie-db:5432/movie_db_dev"
        - name: CAST_SERVICE_HOST_URL
          value: "http://cast-service:8000/api/v1/casts/"
        resources:
          requests:
            memory: "96Mi"
            cpu: "75m"
          limits:
            memory: "384Mi"
            cpu: "300m"
