apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: qa
  labels:
    app: movie-service
    environment: qa
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: movie-service
    environment: qa
