apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: dev
  labels:
    app: nginx          
    environment: dev
    tier: frontend
spec:
  selector:
    app: nginx          
    environment: dev    
  ports:
  - protocol: TCP
    port: 80           
    targetPort: 8080  
    name: http
  type: LoadBalancer