apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: qa
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        upstream cast_service {
            server cast-service:8000;
        }
        upstream movie_service {
            server movie-service:8000;
        }
        server {
            listen 80;
            location /api/v1/casts {
                proxy_pass http://cast_service;
            }
            location /api/v1/movies {
                proxy_pass http://movie_service;
            }
        }
    }