apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-cast-qa
  namespace: qa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-movie-qa
  namespace: qa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
