apiVersion: v1
kind: Secret
metadata:
  name: movie-db-secret
  namespace: qa
type: Opaque
stringData:
  POSTGRES_USER: movie_db_username
  POSTGRES_PASSWORD: movie_db_password_qa
  POSTGRES_DB: movie_db_qa
  DATABASE_URI: postgresql://movie_db_username:movie_db_password_qa@movie-db:5432/movie_db_qa

---
apiVersion: v1
kind: Secret
metadata:
  name: cast-db-secret
  namespace: qa
type: Opaque
stringData:
  POSTGRES_USER: cast_db_username
  POSTGRES_PASSWORD: cast_db_password_qa
  POSTGRES_DB: cast_db_qa
  DATABASE_URI: postgresql://cast_db_username:cast_db_password_qa@cast-db:5432/cast_db_qa
