apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service-prod
  namespace: prod
  labels:
    app: cast-service
    environment: prod
    component: api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: cast-service
      environment: prod
  template:
    metadata:
      labels:
        app: cast-service
        environment: prod
        component: api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
     
      imagePullSecrets:
      - name: dockerhub-secret
     
      containers:
      - name: cast-service
        image: nguetsop/cast-service:v.16.0
        ports:
        - containerPort: 8000
          name: http
       
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: cast-db-secret
              key: DATABASE_URI
        - name: ENVIRONMENT
          value: "prod"
       
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"