apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service-prod
  namespace: prod
  labels:
    app: cast-service
    environment: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cast-service
      environment: prod
  template:
    metadata:
      labels:
        app: cast-service
        environment: prod
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: cast-service
        image: nguetsop/cast-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: "postgresql://cast_db_username:cast_db_password@cast-db:5432/cast_db_dev"
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
