apiVersion: v1
kind: Service
metadata:
  name: cast-db
  namespace: prod
  labels:
    app: cast-db
    environment: prod
    component: database
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: cast-db
    environment: prod