apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: prod
  labels:
    app: movie-service
    environment: prod
    component: api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: movie-service
    environment: prod