apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db-prod
  namespace: prod
  labels:
    app: movie-db
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
      environment: prod
  template:
    metadata:
      labels:
        app: movie-db
        environment: prod
    spec:
      containers:
      - name: postgres
        image: postgres:12.1-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: movie-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: movie-db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: movie-db-secret
              key: POSTGRES_DB
        volumeMounts:
        - name: postgres-data-movie
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: postgres-data-movie
        persistentVolumeClaim:
          claimName: postgres-data-movie-prod