apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: prod
data:
  default.conf: |
    upstream cast_service {
        server cast-service:8000;
    }
    
    upstream movie_service {
        server movie-service:8000;
    }
    
    server {
        listen 8080;
        
        location /api/v1/casts {
            proxy_pass http://cast_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        location /api/v1/movies {
            proxy_pass http://movie_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        location / {
            return 200 '{"status":"ok","environment":"prod","services":["cast-service","movie-service"]}';
            add_header Content-Type application/json;
        }
    }
