apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: prod
  labels:
    app: nginx
    environment: prod
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80           # Port externe (reste 80)
    targetPort: 8080   # Port du container nginx (corrigé)
    protocol: TCP
    name: http
  selector:
    app: nginx
    environment: prod
  sessionAffinity: None