# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-data-cast-prod
#   namespace: prod
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-data-movie-prod
#   namespace: prod
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-cast-prod
  namespace: prod
  labels:
    app: cast-db
    environment: prod
    backup-policy: daily
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Plus réaliste pour production
  storageClassName: fast-ssd  # SSD pour les performances

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-movie-prod
  namespace: prod
  labels:
    app: movie-db
    environment: prod
    backup-policy: daily
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Plus réaliste pour production
  storageClassName: fast-ssd  # SSD pour les performances
